// Copyright 2021 - 2021 The goword Authors. All rights reserved. Use of
// this source code is governed by a MIT license that can be found in
// the LICENSE file.
//
// Package goword providing a set of functions that allow you to write to
// and read from DOCX files. Supports reading and writing
// wordprocessing documents generated by Microsoft Word™ 2007 and later.
// This library needs Go version 1.15 or later.

package goword

import (
	"encoding/xml"
	"sync"
)

type contentTypes struct {
	sync.Mutex
	XMLName   xml.Name       `xml:"http://schemas.openxmlformats.org/package/2006/content-types Types"`
	Overrides []docxOverride `xml:"Override"`
	Defaults  []docxDefault  `xml:"Default"`
}

// docxOverride directly maps the override element in the namespace
// http://schemas.openxmlformats.org/package/2006/content-types
type docxOverride struct {
	PartName    string `xml:",attr"`
	ContentType string `xml:",attr"`
}

// docxDefault directly maps the default element in the namespace
// http://schemas.openxmlformats.org/package/2006/content-types
type docxDefault struct {
	Extension   string `xml:",attr"`
	ContentType string `xml:",attr"`
}
