// Copyright 2021 - 2021 The goword Authors. All rights reserved. Use of
// this source code is governed by a MIT license that can be found in
// the LICENSE file.
//
// Package goword providing a set of functions that allow you to write to
// and read from DOCX files. Supports reading and writing
// wordprocessing documents generated by Microsoft Word™ 2007 and later.
// This library needs Go version 1.15 or later.

package elements

// Background Define background struct
type Background struct {
	// Background Color
	ColorAttr *HexColor `json:"color"`
	// Background Theme Color
	ThemeColorAttr ThemeColor
	// Background Theme Color Tint
	ThemeTintAttr *string
	// Background Theme Color Shade
	ThemeShadeAttr *string
}

func NewBackground() *Background {
	ret := &Background{}
	return ret
}
