// Copyright 2021 - 2021 The goword Authors. All rights reserved. Use of
// this source code is governed by a MIT license that can be found in
// the LICENSE file.
//
// Package goword providing a set of functions that allow you to write to
// and read from DOCX files. Supports reading and writing
// wordprocessing documents generated by Microsoft Word™ 2007 and later.
// This library needs Go version 1.15 or later.

package elements

// Body define wordprocessing Document Body
type Body struct {
	Child  []*BodyChild
	SectPr *SectionProperties
}

type BodyChild struct {
	Paragraph *Paragraph
	Table     *Table
	Sdt       *SdtBlock
}
