// Copyright 2021 - 2021 The goword Authors. All rights reserved. Use of
// this source code is governed by a MIT license that can be found in
// the LICENSE file.
//
// Package goword providing a set of functions that allow you to write to
// and read from DOCX files. Supports reading and writing
// wordprocessing documents generated by Microsoft Word™ 2007 and later.
// This library needs Go version 1.15 or later.

package elements

type HexColorAuto byte

const (
	HexColorAutoUnset HexColorAuto = 0
	HexColorAutoAuto  HexColorAuto = 1
)

type ThemeColor byte

const (
	ThemeColorUnset             ThemeColor = 0
	ThemeColorDark1             ThemeColor = 1
	ThemeColorLight1            ThemeColor = 2
	ThemeColorDark2             ThemeColor = 3
	ThemeColorLight2            ThemeColor = 4
	ThemeColorAccent1           ThemeColor = 5
	ThemeColorAccent2           ThemeColor = 6
	ThemeColorAccent3           ThemeColor = 7
	ThemeColorAccent4           ThemeColor = 8
	ThemeColorAccent5           ThemeColor = 9
	ThemeColorAccent6           ThemeColor = 10
	ThemeColorHyperlink         ThemeColor = 11
	ThemeColorFollowedHyperlink ThemeColor = 12
	ThemeColorNone              ThemeColor = 13
	ThemeColorBackground1       ThemeColor = 14
	ThemeColorText1             ThemeColor = 15
	ThemeColorBackground2       ThemeColor = 16
	ThemeColorText2             ThemeColor = 17
)

type SectionMark byte

const (
	SectionMarkUnset      SectionMark = 0
	SectionMarkNextPage   SectionMark = 1
	SectionMarkNextColumn SectionMark = 2
	SectionMarkContinuous SectionMark = 3
	SectionMarkEvenPage   SectionMark = 4
	SectionMarkOddPage    SectionMark = 5
)

type PageOrientation byte

const (
	PageOrientationUnset     PageOrientation = 0
	PageOrientationPortrait  PageOrientation = 1
	PageOrientationLandscape PageOrientation = 2
)
